spring:
  application:
    name: kotlin-hexagonal-board

  datasource:
    url: jdbc:mysql://localhost:3306/test
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        connection:
          characterEncoding: utf8mb4
          useUnicode: true

  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  port: 8081

# JWT 설정
jwt:
  secret: mySecretKeyForJWTTokenGenerationThatShouldBeLongEnoughForSecurity123
  expiration: 86400000  # 24시간 (밀리초)

logging:
  level:
    com.example.board: DEBUG
    org.springframework.web: DEBUG
